### ISSUE TITLE
Support for Common.FieldControlType/Mandatory

### ISSUE THREAD

**Issue by ttrapp** [oasis-tcs/odata-openapi#11]
At the Moment there is no support for the following annotation type: 
`<Annotation Term="Common.FieldControl" EnumMember="Common.FieldControlType/Mandatory"/>`

Are there any plans to support and this? For me there seems to be no trivial solution sinnce it is not trivial to expand following XPath expression: 

```
<xsl:apply-templates
      select="edm:Property[@Name=../edm:Key/edm:PropertyRef/@Name and not(edm:Annotation[@Term='Org.OData.Core.V1.Computed' or @Term=concat($coreAlias,'.Computed')])]"
      mode="required" />

```

**Comment by ralfhandl** [comment]
Sorry, no plans. 

This annotation was temporarily produced by V2-to-V4-CSDL.xsl, and it turned out that the original intent was already covered by marking all non-computed key properties as "required" via the XPath expression cited above.

The left-over code has been removed with https://github.com/oasis-tcs/odata-openapi/commit/f10035acc8aa092ce288d1ead79aba44443bef6e

Do you have use cases for V2 or V4 services that would originally contain this annotation?

**Comment by ttrapp** [comment]
This flag is important for OData created using the S/4HANA programming model. When you expose a BOPF object using ObjectModel.mandatory annotation you will get the above mentioned OData annotation (see f.e. [https://help.sap.com/viewer/cc0c305d2fab47bd808adcad3ca7ee9d/7.5.9/en-US/896496ecfe4f4f8b857c6d93d4489841.html](https://help.sap.com/viewer/cc0c305d2fab47bd808adcad3ca7ee9d/7.5.9/en-US/896496ecfe4f4f8b857c6d93d4489841.html )). So the translation to "required" makes sense and you get well documented API.

**Comment by ralfhandl** [comment]
Ok, convinced 😄 

https://github.com/oasis-tcs/odata-openapi/commit/d0ec4ef5b2770de3c38b92f8c488164d1c2fbd7c adds a quick hack to recognize Common.FieldControl=Mandatory in the style currently produced by SADL, i.e. annotated with external targeting with namespace-qualified type name and alias-qualified term and enumeration member name, no other variations are recognized.

Please check if that works for your cases, close the issue if it does, and comment if it doesn't.

**Comment by ttrapp** [comment]
Works fine. Thanks!
