### ISSUE TITLE
Output contains a lot of "anyOf" with just one item

### ISSUE THREAD

**Issue by IvanGoncharov** [oasis-tcs/odata-openapi#22]
Since it contains only one item it's basically useless but it creates real problem for generating docs.

Example:
https://github.com/oasis-tcs/odata-openapi/blob/48bd0c5ad52ec50a4d84bdd2da8db6a7814e4ef0/examples/People.openapi3.json#L1166-L1173

**Comment by ralfhandl** [comment]
Hi @IvanGoncharov,

Unfortunately this is necessary to combine `nullable` with `$ref`, and I‘m basically following your advice from https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-192007034. 

I use `anyOf` instead of `allOf` because I use the same construct with properties that can be numbers or strings, e.g.
https://github.com/oasis-tcs/odata-openapi/blob/48bd0c5ad52ec50a4d84bdd2da8db6a7814e4ef0/examples/People.openapi3.json#L1411-L1423

Any less verbose solution to this problem is highly welcome.

Thanks in advance 
Ralf

**Comment by IvanGoncharov** [comment]
@IvanGoncharov Thanks for detail reply 👍

**Comment by ralfhandl** [comment]
@IvanGoncharov In the meantime I switched to `oneOf` in cases that contain only one item because this is represented nicer in Swagger UI.
