### ISSUE TITLE
PATCH generation instead of PUT for OData v4

### ISSUE THREAD

**Issue by azuraka** [oasis-tcs/odata-openapi#24]
This transformer generates PATCH operation instead of PUT for OData (v4.0) even though the backend service supports only PUT.

We have source OData (v2) which we convert to OData (v4) using the [V2-to-V4-CSDL.xsl](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V2-to-V4-CSDL.xsl) and then generate openAPI spec using [V4-CSDL-to-OpenAPI.xsl](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl). The generated openAPI spec has PATCH operation instead of PUT.

Can we have a transformer which generates "V2-CSDL-to-OpenAPI" that retains the operation as PUT instead of converting that to PATCH?

Is there any other way we can approach this problem?

The generated PATCH operation in OpenAPI spec is of no use as backend doesn't support PATCH.

**Comment by ralfhandl** [comment]
OData V2 used the HTTP verb `MERGE` because it was first published before `PATCH` was standardized end of 2010. 

However OData V2's `MERGE` is semantically equivalent to `PATCH`, see https://www.odata.org/blog/support-for-http-patch/, and many OData V2 frameworks support `PATCH` as a synonym for `MERGE`.

Which framework is your service built with?

**Comment by ralfhandl** [comment]
Hi @azuraka, 

I've added a transformation parameter `update-verb` with default `patch` in https://github.com/oasis-tcs/odata-openapi/commit/e52df7cc49f59ba12ed49689a081a9eb3f4bed33.

You can set it e.g. with Xalan command-line parameter `-PARAM update-verb put`.

Hope this helps
Ralf

**Comment by azuraka** [comment]
Hi @ralfhandl,

This will help.

Thanks a lot,
Saurabh
