### ISSUE TITLE
Unable to transform Microsoft Graph APIs metadata

### ISSUE THREAD

**Issue by azuraka** [oasis-tcs/odata-openapi#25]
Hi,

I am trying to transform the following metadata with v4-csdl-to-open-api.xsl:
https://graph.microsoft.com/v1.0/$metadata

But I am getting error. Upon trying online with multiple tools, all throw different errors.

Regards,
Saurabh Jain

**Comment by ralfhandl** [comment]
Hi @azuraka,

I've just successfully converted the Microsoft Graph metadata into OpenAPI 3.0.0 using the latest [XSL transformation](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl).  

The Microsoft Graph metadata is approximately 1 MB, so the transformation took almost 2.5 hours and produced 145 MB of OpenAPI description.

Otherwise no problems.

Thanks
Ralf

**Comment by azuraka** [comment]
Hi @ralfhandl,

I tried the same myself and it is indeed taking this much time for transformation.
Is there anything we can do to reduce this time?
What do you suggest?

Thanks,
Saurabh Jain

**Comment by azuraka** [comment]
Hi @ralfhandl,

Ok will try other transformers.

Regards,
Saurabh Jain

**Comment by ralfhandl** [comment]
Hi @azuraka,

I finally found some time to create a pure JavaScript version of the converter, see https://github.com/oasis-tcs/odata-openapi/tree/master/lib.

It only takes a few seconds to transform Microsoft Graph's metadata, however there are two caveats:
- you need to increase the Node.js heap size, 4 GB are sufficient
- you need to fix a bug in the Graph metadata: it currently contains a complex type with name `image` as well as several function overloads with the same name `image`. This is not allowed per spec, and the tool relies on name uniqueness. Fixing this issue by renaming the complex type to `image_c` and adapting its single use in a property accordingly fixes the issue

Kind regards
Ralf

**Comment by Tiberriver256** [comment]
SO AMAZING!!!!!! Thank you!!!!
