### ISSUE TITLE
Unexpected node

### ISSUE THREAD

**Issue by JhaniCoetzee** [oasis-tcs/odata-openapi#255]
Hi, 

I have a OData metadata file that has a the following child for an EntitySet:
```
<Documentation>
  <Summary></Summary>
  <LongDescription></LongDescription>
  <tagcollection>
    <tag></tag>
    <tag></tag>
  </tagcollection>
</Documentation>
```

I get the error message: "Element EntitySet, unexpected child: Documentation. 

Is there a way that I can add these nodes in the set of just have it ignore them? 

Thank you!

**Comment by ralfhandl** [comment]
Hi @JhaniCoetzee,

Which `<Edmx Version="..."` is your metadata file using?

Thanks in advance 
Ralf

**Comment by JhaniCoetzee** [comment]
Hi Ralf, 

Thanks for the quick response. 
<edmx:Edmx Version="1.0"
  xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx"
  xmlns:atom="http://www.w3.org/2005/Atom">
  <edmx:DataServices m:DataServiceVersion="2.0"

This is for an odata API that we want to consume, so what is in here can't be changed by us, unfortunately. 

Best regards,
Jhani

**Comment by ralfhandl** [comment]
Hi @JhaniCoetzee,

I've prepared a fix for "Element EntitySet, unexpected child: Documentation", see https://github.com/oasis-tcs/odata-csdl-schemas/pull/83.

However, with the _exact_ example above you will then run into "Element Documentation, unexpected child: tagcollection" because the `<tagcollection>` element has the same XML namespace as the `<Documentation>` element, and this is not allowed by the [CSDL specification](https://learn.microsoft.com/en-us/openspecs/windows_protocols/mc-csdl/d51fd43f-1a10-4314-98da-7c1650086bc9):

> The AnnotationElement element and its child elements can belong to any [XML namespace](https://learn.microsoft.com/en-us/openspecs/windows_protocols/mc-csdl/5fb358df-38b0-422d-9640-a636231507a7#gt_485f05b3-df3b-45ac-b8bf-d05f5d185a24) that is not in the list of reserved XML namespaces for CSDL.

If that is the case, you will have to contact the owner of the API to get its metadata fixed.

Thanks in advance
Ralf
