### ISSUE TITLE
OData Query option $search missing from parameters

### ISSUE THREAD

**Issue by avidj** [oasis-tcs/odata-openapi#28]
I am generating the OpenAPI 3.0 specification from the edmx using the transform script. The resulting specification appears fine but cannot be parsed because it lacks the odata $search parameter in the parameters list.metadata.openapi.

editor.swagger.io gives
```
Semantic error at paths./Organizations({ID})/mobilePhoneNumbers.get.parameters.2.$ref
$refs must reference a valid location in the document
Jump to line 871
Semantic error at paths./Persons({ID})/mobilePhoneNumbers.get.parameters.2.$ref
$refs must reference a valid location in the document
Jump to line 1975
Semantic error at paths./SimpleCustomers({ID})/emails.get.parameters.2.$ref
$refs must reference a valid location in the document
Jump to line 2895
Semantic error at paths./SimpleCustomers({ID})/phoneNumbers.get.parameters.2.$ref
$refs must reference a valid location in the document
Jump to line 2985
```

[metadata.xml.zip](https://github.com/oasis-tcs/odata-openapi/files/3223913/metadata.xml.zip)

**Comment by ralfhandl** [comment]
Hi @avidj,

can you please also attach the corresponding $metadata XML file?

Thanks in advance
Ralf

**Comment by ralfhandl** [comment]
Hi @avidj,

The problem is caused by  "association reuse": Entity type `Organizations` has two navigation properties `phoneNumbers` and `mobilePhoneNumbers` that reference the same association element. This is unexpected, and semantically dubious.

Your metadata looks "CDSish": if you use CAP and its CDS compiler, then please try the latest compiler version 1.14.1 which now generates unique association names, so hopefully there will be two separate association elements.

Thanks in advance
Ralf
