### ISSUE TITLE
Edm.DateTime is not converted into Edm.DateTimeOffset or Edm.Date

### ISSUE THREAD

**Issue by snebjorn** [oasis-tcs/odata-openapi#35]
I have this property in my SAP CSDL v2
```xml
<Property Name="someDate" Type="Edm.DateTime" Precision="7" sap:unicode="false" sap:label="Some Date" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
```
According to this the type should have been converted to Edm.DateTimeOffset or Edm.Date
https://github.com/oasis-tcs/odata-openapi/blob/a7887d180578f5c35becbd586c39ecfe8a163066/tools/V2-to-V4-CSDL.xsl#L14

But after running `odata-openapi odatav2.xml` I get this

```jsonc
{
  "openapi": "3.0.0",
  // omitted
  "components": {
    "schemas": {
      "MY_NAMESPACE.FooBar": {
        "type": "object",
        "properties": {
          "someDate": {
            "type": "string",
            "nullable": true,
            "example": "/Date(1492098664000)/",
            "title": "Some Date"
          }
        }
      }
    }
  }
}
```

Am I doing something wrong? I'm assuming the tool automatically runs the v2 to v4 conversion.

**Comment by ralfhandl** [comment]
Your service is still a V2 service and will return a string with a V2 JSON "ticks" value that looks just like the example.

What's happening under the hood:
* V2 metadata is converted to V4 metadata because that is the format expected by the V4-CSDL-to-OpenAPI.xsl transformation
* The latter transformation is called with a parameter telling it the OData version of the original input
* It then produces examples matching the OData version of the original input

**Comment by snebjorn** [comment]
Okay so because the returned date is in that odd V2 JSON "ticks" format the type is `string` and not `Date`?

Makes sense as `/Date(1492098664000)/` isn't a valid JS Date format.
The generated example is a nice touch 👍
