### ISSUE TITLE
Generated enpoints for entities with Nullable='false' NavigationProperties contradict the schema

### ISSUE THREAD

**Issue by tsg2k2** [oasis-tcs/odata-openapi#46]
In the attached sample schema EntityType Other can't be created without association to EntityType Derived (kind of 'not null FK' scenario in databases)
 
One would expect that 
 - POST to /Others will be omitted (as shallow insert allows the creation of Other without association to Derived)
-  POST to /Deriveds/###/Others would be added (to enforce relationship)

[test.api.txt](https://github.com/oasis-tcs/odata-openapi/files/3809678/test.api.txt)

**Comment by ralfhandl** [comment]
Hi @tsg2k2,

POST to /Others is allowed if the client can deep-inserts a new Derived or "binds" to an existing Derived. 

The generated OpenAPI description is intentionally incomplete and "as shallow as possible", it shows "create by association" only for containment navigation properties because that's the only way to create something contained.

Sorry for the late reply
Ralf
