### ISSUE TITLE
is there a path definition for metadata and service document?

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-openapi#66]
Hi, 

Does OData OpenAPI mapping doc define the rules for metadata and service document path? 

Thanks,
-Sam

**Comment by ralfhandl** [comment]
Hi Sam,

No, it doesn’t. We assumed that only OData-aware clients would use the service document and metadata document, and these clients wouldn’t be interested in the OpenAPI document as it contains less information than $metadata. 

Do you have situations where OpenAPI clients would be interested in the service or metadata document?

Thanks in advance 
Ralf

**Comment by adriano-campanhola** [comment]
Hi @ralfhandl, in our use case, we publish the API's on Azure API Management, which will refuse any operation that is not currently defined on the interface. If we try to utilize any of the api's on a SAPUI5/UI5 frontend, those could require the $metadata operation, as the frontend could utilize it on startup.

**Comment by ralfhandl** [comment]
> refuse any operation that is not currently defined on the interface

Well, then you've got a problem: the OpenAPI files are intentionally incomplete and only show the most prominent paths, they don't attempt to show all possible paths - given that OData's path syntax is recursive and based on the service's resource model, showing all possible paths is unreasonable.

The `containment` example shows a potentially endless recursion, and you can reach the contained folders only via their - potentially unlimited - chain of parent folders:

https://github.com/oasis-tcs/odata-openapi/blob/15220b9a26a2e6c40ad4dd57e1712f275d23b08d/examples/containment.xml#L98-L105

The generated OpenAPI file stops after five levels:

https://github.com/oasis-tcs/odata-openapi/blob/15220b9a26a2e6c40ad4dd57e1712f275d23b08d/examples/containment.openapi3.json#L4704

Would Azure API Management allow to go deeper because paths for level 15 start with a documented prefix, or would it prevent accessing anything below level 5?

**Comment by adriano-campanhola** [comment]
Yep, it's a current a limitation from Azure API Management in [general](https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions), but so far we haven't had to go deeper than a few levels.

**Comment by ralfhandl** [comment]
> Recursion - API Management doesn't support definitions defined recursively (for example, schemas referring to themselves).

So this will be problematic:

https://github.com/oasis-tcs/odata-openapi/blob/15220b9a26a2e6c40ad4dd57e1712f275d23b08d/examples/containment.openapi3.json#L4894-L4910

Seems like you will have to design your services carefully to match the limitations of your API Management solution, and you'll have to tweak the OpenAPI files or fork this generator to suit its specific needs.
